---
name: Checking code quality

on: [push, pull_request]

jobs:

  ci-qlty:

    runs-on: ubuntu-latest

    container: fedorapython/fedora-python-tox:latest

    strategy:
      fail-fast: false

    steps:

      - name: Checkout the codebase current state
        uses: actions/checkout@v6

      - name: Install the base dependencies
        run: |
             python3 -m pip install --upgrade uv tox

      - name: Check the correctness of the project config
        run: |
             uv sync --extra dev

      - name: Check the quality of the code
        run: |
             tox -e cleaning
